# Generated by Django 4.2.2 on 2023-06-18 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                ("photo", models.FileField(upload_to="category/")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
            ],
            options={
                "verbose_name": "Часто Задаваемый Вопрос",
                "verbose_name_plural": "Часто Задаваемые Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to="photos/", verbose_name="Картина"),
                ),
            ],
            options={
                "verbose_name": "Картина",
                "verbose_name_plural": "Картинки",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                ("photo", models.FileField(upload_to="category/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="courses.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "ПодКатегория",
                "verbose_name_plural": "ПодКатегории",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание теста"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Courses",
                        to="courses.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Courses",
                        to="courses.photo",
                        verbose_name="Картина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cпециальность",
                "verbose_name_plural": "Cпециальности",
            },
        ),
    ]
