# Generated by Django 4.2.2 on 2023-06-18 05:21
# Generated by Django 4.2.2 on 2023-06-17 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, verbose_name='Регион/Область')),
                ('adress', models.CharField(max_length=255, verbose_name='Адресс')),
            ],
            options={
                'verbose_name': 'Адресс',
                'verbose_name_plural': 'Адресса',
            },
        ),
        migrations.CreateModel(
            name="Adress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(max_length=255, verbose_name="Регион/Область"),
                ),
                ("adress", models.CharField(max_length=255, verbose_name="Адресс")),
            ],
            options={
                "verbose_name": "Адресс",
                "verbose_name_plural": "Адресса",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=255, verbose_name="Ответ")),
                ("is_true", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.CreateModel(
            name="FormForUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=55, verbose_name="Имя Пользователя"),
                ),
                (
                    "surname",
                    models.CharField(
                        max_length=255, verbose_name="Фамилия Пользователя"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер Пользователя"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, verbose_name="Email Пользователя"
                    ),
                ),
            ],
            options={
                "verbose_name": "Форма для пользователя",
                "verbose_name_plural": "Форма для пользователей",
            },
        ),
        migrations.CreateModel(
            name="OfflineRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_selection",
                    models.DateTimeField(verbose_name="Выбор даты и времени"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Утверждено"),
                ),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя Пользователя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия Пользователя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер Пользователя')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Пользователя')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FormForUsers', to='tests.adress', verbose_name='Адресс')),
            ],
            options={
                "verbose_name": "Заявка на запись на офлайн",
                "verbose_name_plural": "Заявки на запись на офлайн",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Текст Вопроса"),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="название теста"),
                ),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_answers",
                    models.PositiveIntegerField(
                        verbose_name="Количество правильных ответов"
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        verbose_name="Общее количество вопросов"
                    ),
                ),
                (
                    "date_completed",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_result",
                        to="tests.test",
                        verbose_name="Тест",
                    ),
                ),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
                ('is_true', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', verbose_name='Вопрос')),
            ],
            options={
                "verbose_name": "Результат теста",
                "verbose_name_plural": "Результаты тестов",
            },
        ),
    ]
